### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by umlaeute** [grrrr/upp#2]
subject says it all...

**Comment by grrrr** [comment]
i will once there is one

**Comment by umlaeute** [comment]
oh; i thought there was at least `0.1`, as uploaded via [deken](http://puredata.info/Members/thomas/software/upp/0.1/upp-v0.1--externals.zip)

**Comment by grrrr** [comment]
good point! I will assert the usability and make a genuine synchronized release. Thanks

**Comment by grrrr** [comment]
done!
